# Uncomment the next line to define a global platform for your project
 platform :ios, '99.0'

target 'TableViewTest' do

pod 'MJRefresh', '~> 3.1.13'
pod 'MJExtension', '~> 3.0.13'
pod 'HYBNetworking', '~> 3.3.1'
pod 'SDWebImage', '~> 4.1.0'
pod 'libextobjc'

end
